---

services:

  agnosticd-server:
    image: docker.io/tonykay/agnosticd-ansible-2.9-vsc
    container_name: agnosticd
    hostname: agnosticd
    volumes:
      - ~/repos/agnosticd/repo/agnosticd:/home/devops/agnosticd
      - ~/secrets:/home/devops/secrets  
    ports:
      - 8000:8080
    environment:
      - "DOCKER_USER=$USER"
      - "PASSWORD=changeme"
    restart: unless-stopped
